name: Build, test, package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  itk-git-tag: "v5.4.0"
  itk-wheel-tag: "v5.4.0"
  # v5.4.0 + fixes
  itk-python-package-tag: "a52d9b596b4f0da5ddb770ee99851e5c65ca3053"

jobs:
  build-test-cxx:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 3
      matrix:
        os: [ubuntu-22.04, windows-2022, macos-12]
        include:
          - os: ubuntu-22.04
            c-compiler: "gcc"
            cxx-compiler: "g++"
            cmake-build-type: "MinSizeRel"
          - os: windows-2022
            c-compiler: "cl.exe"
            cxx-compiler: "cl.exe"
            cmake-build-type: "Release"
          - os: macos-12
            c-compiler: "clang"
            cxx-compiler: "clang++"
            cmake-build-type: "MinSizeRel"

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install ninja
        python -m pip install cookiecutter

    - name: Get specific version of CMake, Ninja
      uses: lukka/get-cmake@v3.29.0

    - name: Download ITK
      run: |
        cd ..
        git clone https://github.com/InsightSoftwareConsortium/ITK.git
        cd ITK
        git checkout ${{ env.itk-git-tag }}

    - name: Build ITK
      if: matrix.os != 'windows-2022'
      run: |
        cd ..
        mkdir ITK-build
        cd ITK-build
        cmake -DCMAKE_C_COMPILER:FILEPATH="${{ matrix.c-compiler }}" -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_CXX_COMPILER="${{ matrix.cxx-compiler }}" -DCMAKE_BUILD_TYPE:STRING=${{ matrix.cmake-build-type }} -DBUILD_TESTING:BOOL=OFF -GNinja ../ITK
        ninja

    - name: Build ITK
      if: matrix.os == 'windows-2022'
      run: |
        cd ..
        mkdir ITK-build
        cd ITK-build
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cmake -DCMAKE_C_COMPILER:FILEPATH="${{ matrix.c-compiler }}" -DBUILD_SHARED_LIBS:BOOL=ON -DCMAKE_CXX_COMPILER="${{ matrix.cxx-compiler }}" -DCMAKE_BUILD_TYPE:STRING=${{ matrix.cmake-build-type }} -DBUILD_TESTING:BOOL=OFF -GNinja ../ITK
        ninja
      shell: cmd

    - name: Fetch CTest driver script
      run: |
        curl -L https://raw.githubusercontent.com/InsightSoftwareConsortium/ITK/dashboard/itk_common.cmake -O

    - name: Evaluate template
      shell: bash
      run: |
        python -m cookiecutter --no-input --output-dir "${GITHUB_WORKSPACE}/../Evaluated" "${GITHUB_WORKSPACE}"
        mkdir "${GITHUB_WORKSPACE}/../Evaluated/ITKModuleTemplate/.git"

    - name: Configure CTest script
      shell: bash
      run: |
        operating_system="${{ matrix.os }}"
        cat > dashboard.cmake << EOF
        set(CTEST_SITE "GitHubActions")
        file(TO_CMAKE_PATH "\$ENV{GITHUB_WORKSPACE}/.." CTEST_DASHBOARD_ROOT)
        file(TO_CMAKE_PATH "\$ENV{GITHUB_WORKSPACE}/../Evaluated/ITKModuleTemplate" CTEST_SOURCE_DIRECTORY)
        file(TO_CMAKE_PATH "\$ENV{GITHUB_WORKSPACE}/../build" CTEST_BINARY_DIRECTORY)
        set(dashboard_source_name "${GITHUB_REPOSITORY}")
        if(ENV{GITHUB_REF} MATCHES "main")
          set(branch "-main")
          set(dashboard_model "Continuous")
        else()
          set(branch "-${GITHUB_REF}")
          set(dashboard_model "Experimental")
        endif()
        set(CTEST_BUILD_NAME "${GITHUB_REPOSITORY}-${operating_system}-\${branch}")
        set(CTEST_UPDATE_VERSION_ONLY 1)
        set(CTEST_TEST_ARGS \${CTEST_TEST_ARGS} PARALLEL_LEVEL \${PARALLEL_LEVEL})
        set(CTEST_BUILD_CONFIGURATION "Release")
        set(CTEST_CMAKE_GENERATOR "Ninja")
        set(CTEST_CUSTOM_WARNING_EXCEPTION
          \${CTEST_CUSTOM_WARNING_EXCEPTION}
          # macOS Azure VM Warning
          "ld: warning: text-based stub file"
          )
        set(dashboard_no_clean 1)
        set(ENV{CC} ${{ matrix.c-compiler }})
        set(ENV{CXX} ${{ matrix.cxx-compiler }})
        if(WIN32)
          set(ENV{PATH} "\${CTEST_DASHBOARD_ROOT}/ITK-build/bin;\$ENV{PATH}")
        endif()
        set(dashboard_cache "
        ITK_DIR:PATH=\${CTEST_DASHBOARD_ROOT}/ITK-build
        BUILD_TESTING:BOOL=ON
        ")
        string(TIMESTAMP build_date "%Y-%m-%d")
        message("CDash Build Identifier: \${build_date} \${CTEST_BUILD_NAME}")
        message("CTEST_SITE = \${CTEST_SITE}")
        include(\${CTEST_SCRIPT_DIRECTORY}/itk_common.cmake)
        EOF
        cat dashboard.cmake

    - name: Build and test
      if: matrix.os != 'windows-2022'
      run: |
        ctest --output-on-failure -j 2 -V -S dashboard.cmake

    - name: Build and test
      if: matrix.os == 'windows-2022'
      run: |
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        ctest --output-on-failure -j 2 -V -S dashboard.cmake
      shell: cmd

  build-linux-python-packages:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["38", "39", "310", "311"]

    steps:
    - uses: actions/checkout@v3

    - name: 'Free up disk space'
      run: |
        # Workaround for https://github.com/actions/virtual-environments/issues/709
        df -h
        sudo apt-get clean
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h

    - name: 'Fetch build dependencies'
      shell: bash
      run: |
        sudo apt install zstd
        unzstd --version

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Get specific version of CMake, Ninja
      uses: lukka/get-cmake@v3.29.0

    - name: Evaluate template
      shell: bash
      run: |
        python -m pip install cookiecutter
        python -m cookiecutter --no-input --output-dir "${GITHUB_WORKSPACE}/Evaluated" "${GITHUB_WORKSPACE}"
        mkdir "${GITHUB_WORKSPACE}/Evaluated/ITKModuleTemplate/.git"

    - name: 'Fetch build script'
      run: |
        curl -L https://raw.githubusercontent.com/InsightSoftwareConsortium/ITKPythonPackage/${{ env.itk-python-package-tag }}/scripts/dockcross-manylinux-download-cache-and-build-module-wheels.sh -O
        chmod u+x dockcross-manylinux-download-cache-and-build-module-wheels.sh

    - name: 'Build 🐍 Python 📦 package'
      run: |
        cd "${GITHUB_WORKSPACE}/Evaluated/ITKModuleTemplate"
        export ITK_PACKAGE_VERSION=${{ env.itk-wheel-tag }}
        export ITKPYTHONPACKAGE_TAG=${{ env.itk-python-package-tag }}
        for manylinux_version in "_2_28" "2014"; do
          rm -rf ITKPythonPackage
          export MANYLINUX_VERSION=${manylinux_version}
          echo "Building for manylinux specialization ${MANYLINUX_VERSION}"
          ../../dockcross-manylinux-download-cache-and-build-module-wheels.sh cp${{ matrix.python-version }}
        done

    - name: Publish Python package as GitHub Artifact
      uses: actions/upload-artifact@v3
      with:
        name: LinuxWheel${{ matrix.python-version }}
        path: Evaluated/ITKModuleTemplate/dist

  build-macos-python-packages:
    runs-on: macos-12
    strategy:
      max-parallel: 2
      matrix:
        python-version: ["38", "39", "310", "311"]

    steps:
    - uses: actions/checkout@v4

    - name: 'Specific XCode version'
      run: |
        sudo xcode-select -s "/Applications/Xcode_13.2.1.app"

    - name: Get specific version of CMake, Ninja
      uses: lukka/get-cmake@v3.29.0

    - name: 'Fetch build script'
      run: |
        curl -L https://raw.githubusercontent.com/InsightSoftwareConsortium/ITKPythonPackage/${{ env.itk-python-package-tag }}/scripts/macpython-download-cache-and-build-module-wheels.sh -O
        chmod u+x macpython-download-cache-and-build-module-wheels.sh

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Evaluate template
      shell: bash
      run: |
        python -m pip install cookiecutter
        python -m cookiecutter --no-input --output-dir "${GITHUB_WORKSPACE}/Evaluated" "${GITHUB_WORKSPACE}"
        mkdir "${GITHUB_WORKSPACE}/Evaluated/ITKModuleTemplate/.git"

    - name: 'Build 🐍 Python 📦 package'
      run: |
        cd "${GITHUB_WORKSPACE}/Evaluated/ITKModuleTemplate"
        export ITK_PACKAGE_VERSION=${{ env.itk-wheel-tag }}
        export ITKPYTHONPACKAGE_TAG=${{ env.itk-python-package-tag }}
        export MACOSX_DEPLOYMENT_TARGET=10.9
        ../../macpython-download-cache-and-build-module-wheels.sh

    - name: Publish Python package as GitHub Artifact
      uses: actions/upload-artifact@v3
      with:
        name: MacOSWheels
        path: Evaluated/ITKModuleTemplate/dist

  build-windows-python-packages:
    runs-on: windows-2022
    strategy:
      max-parallel: 2
      matrix:
        python-version-minor: ["8", "9", "10", "11"]

    steps:
    - uses: actions/checkout@v3

    - name: 'Install Python'
      run: |
        $pythonArch = "64"
        $pythonVersion = "3.${{ matrix.python-version-minor }}"
        iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/scikit-build/scikit-ci-addons/master/windows/install-python.ps1'))

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Get specific version of CMake, Ninja
      uses: lukka/get-cmake@v3.29.0

    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Evaluate template
      shell: bash
      run: |
        python -m pip install cookiecutter
        python -m cookiecutter --no-input --output-dir "${GITHUB_WORKSPACE}/Evaluated" "${GITHUB_WORKSPACE}"
        mkdir "${GITHUB_WORKSPACE}/Evaluated/ITKModuleTemplate/.git"

    - name: 'Fetch build dependencies'
      shell: bash
      run: |
        cd Evaluated/ITKModuleTemplate
        curl -L "https://github.com/InsightSoftwareConsortium/ITKPythonBuilds/releases/download/${{ env.itk-wheel-tag }}/ITKPythonBuilds-windows.zip" -o "ITKPythonBuilds-windows.zip"
        7z x ITKPythonBuilds-windows.zip -o/c/P -aoa -r
        curl -L "https://data.kitware.com/api/v1/file/5c0ad59d8d777f2179dd3e9c/download" -o "doxygen-1.8.11.windows.bin.zip"
        7z x doxygen-1.8.11.windows.bin.zip -o/c/P/doxygen -aoa -r
        curl -L "https://data.kitware.com/api/v1/file/5bbf87ba8d777f06b91f27d6/download/grep-win.zip" -o "grep-win.zip"
        7z x grep-win.zip -o/c/P/grep -aoa -r

        # Update step for skbuild issue in v5.3.0 build archive
        echo "Updating ITKPythonPackage build scripts to ${{ env.itk-python-package-tag }}"
        pushd /c/P/IPP
        git remote add InsightSoftwareConsortium https://github.com/InsightSoftwareConsortium/ITKPythonPackage.git --tags
        git fetch InsightSoftwareConsortium
        git checkout ${{ env.itk-python-package-tag }}
        git status
        popd

    - name: 'Build 🐍 Python 📦 package'
      shell: cmd
      run: |
        cd Evaluated/ITKModuleTemplate
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        set PATH=C:\P\grep;%PATH%
        set CC=cl.exe
        set CXX=cl.exe
        C:\Python3${{ matrix.python-version-minor }}-x64\python.exe C:\P\IPP\scripts\windows_build_module_wheels.py --py-envs "3${{ matrix.python-version-minor }}-x64"

    - name: Publish Python package as GitHub Artifact
      uses: actions/upload-artifact@v3
      with:
        name: WindowWheel3.${{ matrix.python-version-minor }}
        path: Evaluated/ITKModuleTemplate/dist
